#source from wheeltec_nav2: param_mini_diff.yaml
bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_footprint
    odom_topic: /camera_init
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 90
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      # - nav2_goal_updated_controller_bt_node
      - nav2_is_battery_low_condition_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 10.0 #20.0                    # 控制器频率10Hz
    min_x_velocity_threshold: 0.001                     # x方向最小速度阈值   
    min_y_velocity_threshold: 0.001                     # y方向最小速度阈值（侧向移动）, 差速机器人没有y轴方向的移动. 4wd-4ws有y轴方向移动
    min_theta_velocity_threshold: 0.001                 # 角速度最小阈值
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"         # 进度检查器插件
    goal_checker_plugins: ["general_goal_checker"]      # 目标检查器插件 "precise_goal_checker"
    controller_plugins: ["FollowPath"]                  # 控制器插件（DWB局部规划器）

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"  # 简单进度检查器
      #以下两个是进度检查器的关键参数，用于检测机器人是否卡住：
      required_movement_radius: 0.4 #0.5                # 要求移动半径0.4m（10秒内需移动此距离)，调大：减少误报，允许机器人在复杂环境中缓慢移动，但是可能延迟卡住检测，机器人实际卡住时反应变慢； 调小，更敏感检测卡住情况，但是在拥挤环境中容易触发恢复行为，打断正常导航
      movement_time_allowance: 10.0                     # 移动时间允许值10s，调大：给机器人更多时间完成机动； 调小：快速响应卡住情况，但是过早触发恢复行为，打断正常导航
    # Goal checker parameters
    #precise_goal_checker:
    #  plugin: "nav2_controller::SimpleGoalChecker"
    #  xy_goal_tolerance: 0.25
    #  yaw_goal_tolerance: 0.25
    #  stateful: True
    general_goal_checker:
      stateful: True                                   # True:需要持续满足条件才确认到达,避免因短暂位置波动造成的误判
      plugin: "nav2_controller::SimpleGoalChecker"     # 简单目标检查器
      xy_goal_tolerance: 0.35 #0.25                     # xy位置容差0.2m
      yaw_goal_tolerance: 0.3 #0.4                     # 朝向容差0.4弧度（约23度）
    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"              # DWB局部规划器插件
      debug_trajectory_details: True                   # 调试轨迹详情
      min_vel_x: 0.0 #-1.0                             # 最小x线速度（可后退为负值）
      min_vel_y: 0.0                                   # 允许负向侧移
      max_vel_x: 0.3 #1.0                              # 最大x线速度0.5m/s
      max_vel_y: 0.0                                   # 增加侧向移动速度限制
      max_vel_theta: 1.0 #1.5                          # 最大角速度1.5rad/s
      min_speed_xy: 0.0
      max_speed_xy: 0.5 #1.0
      min_speed_theta: 0.0
      # Add high threshold velocity for turtlebot 3 issue.
      # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
      acc_lim_x: 0.5                                   # x线加速度限制0.5m/s²
      acc_lim_y: 0.0                                   # 增加y方向加速度限制                   
      acc_lim_theta: 1.0 #1.0                          # 角加速度限制3.0rad/s²
      decel_lim_x: -0.5                                # x线减速度限制-0.5m/s²
      decel_lim_y: 0.0                                # 增加y方向减速度限制
      decel_lim_theta: -3.0 #-1.0
      # 采样参数 - 增加y方向采样
      vx_samples: 20                                   # x速度采样数20个
      vy_samples: 0                                   # 增加y速度采样数
      vtheta_samples: 20                               # 角速度采样数20个
      sim_time: 2.5 # 1.7                              # 轨迹前向模拟时间2.5s
      linear_granularity: 0.03                         # 离散化参数，线性粒度0.05m， 调小：轨迹平滑，但计算量增加
      angular_granularity: 0.02                       # 离散化参数，角度粒度0.02rad，调小：旋转控制更精确流畅，但计算量增加
      # 其他参数
      transform_tolerance: 0.2 #0.2                    # 变换容差0.2s， 调大：对TF延迟更宽容，但可能使用过时的坐标变换； 调小：要求更实时的TF数据，但可能因短暂延迟而失败
      xy_goal_tolerance: 0.25 #0.25                     # 目标位置容差0.2m
      trans_stopped_velocity: 0.15                     # 停止判断速度阈值0.15m/s，调大：更容易判断为停止，但可能误判低速移动为停止；调小：更难判断为停止，但停止判断可能延迟；
      short_circuit_trajectory_evaluation: True
      stateful: True
      # 轨迹评价器 (Critics)
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      # critics: ["Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      # 障碍物避让
      BaseObstacle.scale: 0.2 #0.04                    # 基础障碍物代价权重0.2
      # 路径对齐 - 调整权重以支持侧向移动
      PathAlign.scale: 150.0  #50.0 100.0              # 路径对齐权重150.0
      PathAlign.forward_point_distance: 0.2            # 前视点距离0.1m， 调大：更前瞻的路径跟踪，转弯更平滑，但可能会切完； 调小：转弯更尖锐，但可能抖动
      # 目标对齐
      GoalAlign.scale: 15.0 #10.0                      # 目标对齐权重15.0
      GoalAlign.forward_point_distance: 0.15            # 前视点距离0.15m， 调大：提前开始对准目标，最终朝向更准确； 调小：接近目标时才对准，可能最终朝向偏差较大
      # 距离代价
      PathDist.scale: 100.0 #50.0 80.0                 # 路径距离权重100.0
      GoalDist.scale: 10.0                             # 目标距离权重10.0
      # 目标旋转
      RotateToGoal.scale: 32.0                         # 旋转到目标权重32.0
      RotateToGoal.slowing_factor: 5.0                 # 减速因子5.0
      RotateToGoal.lookahead_time: -1.0                # 前视时间-1.0（禁用），禁用(-1):使用 GoalAlign.forward_point_distance: 0.1 的固定距离,在距离目标0.1米处开始旋转对准; 启用(正值):前视距离 = 当前速度 × lookahead_time
      allow_rotating_to_goal: True                     #开启/关闭到达目标后的旋转

# controller_server:
#   ros__parameters:
#     odom_topic: /camera_init
#     use_sim_time: True
#     controller_frequency: 5.0
#     controller_plugin_types: ["teb_local_planner::TebLocalPlannerROS"]
#     controller_plugins: ["FollowPath"]

#     # Add goal checker configuration for TEB planner
#     goal_checker_plugins: ["general_goal_checker"]
#     progress_checker_plugin: "progress_checker"
    
#     # Progress checker parameters
#     progress_checker:
#       plugin: "nav2_controller::SimpleProgressChecker"
#       required_movement_radius: 0.3
#       movement_time_allowance: 10.0
    
#     # Goal checker parameters
#     general_goal_checker:
#       plugin: "nav2_controller::SimpleGoalChecker"
#       xy_goal_tolerance: 0.25
#       yaw_goal_tolerance: 0.4
#       stateful: True

#     FollowPath:
#       plugin: teb_local_planner::TebLocalPlannerROS

#       # Add goal tolerance parameters for TEB
#       xy_goal_tolerance: 0.25
#       yaw_goal_tolerance: 0.4
#       free_goal_vel: False
#       complete_global_plan: True

#       teb_autosize: 1.0
#       dt_ref: 0.3
#       dt_hysteresis: 0.1
#       max_samples: 500
#       global_plan_overwrite_orientation: False
#       allow_init_with_backwards_motion: False
#       max_global_plan_lookahead_dist: 3.0
#       global_plan_viapoint_sep: 0.3
#       global_plan_prune_distance: 1.0
#       exact_arc_length: False
#       feasibility_check_no_poses: 2
#       publish_feedback: False
          
#       # Robot
#       min_vel_x: 0.0        
#       max_vel_x: 0.3
#       max_vel_theta: 0.5 
#       acc_lim_x: 1.0
#       acc_lim_theta: 1.5

#       footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
#         type: "polygon"
#         # radius: 0.20 # for type "circular"
#         vertices: "[-0.36, -0.25], [-0.36, 0.25], [0.36, 0.25], [0.36, -0.25]"

#       # # GoalTolerance
#       # free_goal_vel: False
          
#       # Obstacles
#       min_obstacle_dist: 0.3
#       inflation_dist: 0.5
#       include_costmap_obstacles: True
#       costmap_obstacles_behind_robot_dist: 1.0
#       obstacle_poses_affected: 15

#       dynamic_obstacle_inflation_dist: 0.5
#       include_dynamic_obstacles: True 

#       costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
#       costmap_converter_spin_thread: True
#       costmap_converter_rate: 5

#       # Optimization
#       no_inner_iterations: 3
#       no_outer_iterations: 2
#       optimization_activate: True
#       optimization_verbose: False
#       penalty_epsilon: 0.1
#       obstacle_cost_exponent: 4.0
#       weight_max_vel_x: 1.0 # Increased from 0.5 to penalize high speeds more
#       weight_max_vel_theta: 1.0 # Increased from 0.5 to penalize high angular speeds more
#       weight_acc_lim_x: 0.5
#       weight_acc_lim_theta: 10.5
#       weight_kinematics_nh: 1000.0
#       weight_kinematics_forward_drive: 3.0
#       weight_kinematics_turning_radius: 1.0
#       weight_optimaltime: 1.0 # must be > 0
#       weight_shortest_path: 0.0
#       weight_obstacle: 50.0
#       weight_inflation: 0.2
#       weight_dynamic_obstacle: 10.0 # not in use yet
#       weight_dynamic_obstacle_inflation: 0.2
#       weight_viapoint: 50.0
#       weight_adapt_factor: 2.0

#       # Homotopy Class Planner
#       enable_homotopy_class_planning: True
#       enable_multithreading: False # Disabled for stability
#       max_number_classes: 2
#       selection_cost_hysteresis: 5.0
#       selection_prefer_initial_plan: 1.0
#       selection_obst_cost_scale: 1.0
#       selection_alternative_time_cost: True

#       roadmap_graph_no_samples: 10
#       roadmap_graph_area_width: 5.0
#       roadmap_graph_area_length_scale: 1.0
#       h_signature_prescaler: 0.5
#       h_signature_threshold: 0.1
#       obstacle_heading_threshold: 0.45
#       switching_blocking_period: 0.0
#       viapoints_all_candidates: True
#       delete_detours_backwards: True
#       max_ratio_detours_duration_best_duration: 3.0
#       visualize_hc_graph: False
#       visualize_with_time_as_z_axis_scale: 0.0

#       # Recovery
#       shrink_horizon_backup: True
#       shrink_horizon_min_duration: 10.0
#       oscillation_recovery: True
#       oscillation_v_eps: 0.1
#       oscillation_omega_eps: 0.1
#       oscillation_recovery_min_duration: 10.0
#       oscillation_filter_duration: 10.0

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 15.0           # 更新频率20Hz（高频更新，用于实时避障）
      publish_frequency: 5.0
      global_frame: map #odom_combined      # 全局坐标系（里程计融合坐标系）
      robot_base_frame: base_footprint # 机器人基座坐标系
      use_sim_time: False
      rolling_window: true   # 使用滚动窗口模式（local_costmap地图随机器人移动）
      width: 5               # local_costmap地图宽度5米
      height: 5              # local_costmap地图高度5米
      resolution: 0.05       # 分辨率0.05m/像素
      # robot_radius: 0.3      # 机器人半径0.3m（用于圆形机器人模型）
      footprint: "[ [-0.36, -0.25], [-0.36, 0.25], [0.36, 0.25], [0.36, -0.25] ]"
      plugins: ["voxel_layer", "inflation_layer"] # 使用的图层
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer" # 膨胀图层插件
        cost_scaling_factor: 3.0 # 3.0 10.0       # 代价缩放因子3.0（控制代价衰减速度),这个值越大，安全区域越小，越靠近障碍物行驶
        inflation_radius: 0.25   # 0.25 0.5       # local_costmap膨胀半径0.35m
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer" # 3D体素图层插件
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0                         # 原点Z坐标，表示体素地图的Z轴原点位于地面（z=0m）高度
        z_resolution: 0.05                    # Z轴分辨率0.05m
        z_voxels: 16                          # Z轴体素数（16×0.05=0.8m高度）
        max_obstacle_height: 2.0              # 最大障碍物高度2.0m
        mark_threshold: 1                     # 标记阈值（1个体素即视为障碍物)
        observation_sources: pointcloud       # **使用mid-360数据/pointcloud进行避障**
        pointcloud:
          topic: /livox/lidar/pointcloud     # mid-360点云数据topic
          max_obstacle_height: 1.5           # 最大障碍物高度1.5m
          min_obstacle_height: 0.32          # 最小障碍物高度0.12m（过滤地面，由于点云误差设置成0.12m）
          clearing: True                     # 启用障碍物清除, 设置True：当传感器检测到之前标记为障碍物的区域现在为空闲时，清除该区域的障碍物标记。
          marking: True                      # 启用障碍物标记，设置True：当传感器检测到障碍物时，在代价地图中标记相应区域。
          data_type: "PointCloud2"           # 数据类型
          raytrace_max_range: 5.0            # 光线追踪最大范围4m  （调大能更好的清除远处障碍物，增加计算开销；调小减少计算量，减小远处传感器噪声影响）
          raytrace_min_range: 0.05           # 光线追踪最小范围0.05m (调大能更好的减少近处噪声，但近处障碍物清除能力下降；调小能够更精确的近处障碍物处理，增加计算开销）
          obstacle_max_range: 5.0            # 障碍物检测最大范围4m(距离机器人)
          obstacle_min_range: 0.01           # 障碍物检测最小范围0.01m(距离机器人)

      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0                   # 更新频率5Hz（低频更新）
      publish_frequency: 2.0
      global_frame: map
      robot_base_frame: base_footprint
      use_sim_time: False
      # robot_radius: 0.3                       # 机器人半径0.3m（用于圆形机器人模型）
      footprint: "[ [-0.36, -0.25], [-0.36, 0.25], [0.36, 0.25], [0.36, -0.25] ]"
      resolution: 0.05
      track_unknown_space: true               # 跟踪未知空间（为true时未知区域可通行）
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        mark_threshold: 1
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: pointcloud       # **使用mid-360数据/pointcloud进行避障**
        pointcloud:
          topic: /livox/lidar/pointcloud     # mid-360点云数据topic
          max_obstacle_height: 1.5          
          min_obstacle_height: 0.32
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 10.0
          raytrace_min_range: 0.1
          obstacle_max_range: 3.0
          obstacle_min_range: 0.01
          observation_persistence: 0.0     #障碍物持久性，0.0：实时性最好，但对传感器噪声更敏感；调大对短暂障碍物更鲁棒，减少障碍物闪烁，缺点是致已移动障碍物的残留
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"      # 静态地图图层
        map_subscribe_transient_local: True         
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 10.0 #5.0              # 代价缩放因子
        inflation_radius: 0.45                      # 膨胀半径
        decay_time: 0.0                             # 0.0表示代价值立即衰减到0； 增大，比如从0.0改为1.0（提供更平滑的代价衰减），提供历史障碍物信息，对短暂遮挡更稳定，缺点是导致已清除障碍物的代价值残留
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: ""
    frame_id: "map"

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 1.0                                  # 0.5 增加路径规划容差，允许更灵活的路径
      use_astar: false
      allow_unknown: true
      cost_factor: 3.0                                # 5.0 降低代价因子，规划更直接的路径

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

smoother_server:
  ros__parameters:
    use_sim_time: False #True
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1500                                   # 1000 增加最大迭代次数，获得更平滑路径
      do_refinement: True

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    global_frame: map #odom_combined
    robot_base_frame: base_footprint
    transform_tolerance: 0.2
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.5  #0.7
    min_rotational_vel: 0.1  #0.3
    rotational_acc_lim: 0.5  #0.3

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200
